---
#####
dist : trusty
sudo : required
group : edge

language : node_js
services : [ "docker" ]
node_js : [ "8" ]

notifications :
  email :
    recipients :
      - $EMAIL
    on_success : never
    on_failure : always

before_install :
  - npm install -g yarn

install :
  - yarn install

script :
  - yarn run ci
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ] ; then echo "latest" ; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $TRAVIS_REPO_SLUG:$TRAVIS_COMMIT .
  - docker tag $TRAVIS_REPO_SLUG:$TRAVIS_COMMIT $TRAVIS_REPO_SLUG:$TRAVIS_BUILD_NUMBER-$TRAVIS_BRANCH
  - docker tag $TRAVIS_REPO_SLUG:$TRAVIS_COMMIT $TRAVIS_REPO_SLUG:$TAG
  - docker images -a
